name: Build Vue
on: [push]
permissions:
  actions: write
  pages: write
  contents: write
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: "pure-english"
        reponame: "name-generator"
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged